name: Deploy Laravel API to VPS

on:
  push:
    branches:
      - main # Workflow terpicu otomatis saat push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploying code via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          port: ${{ secrets.VPS_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/catalog-api
            # 1. Simpan commit hash sebelum git pull untuk deteksi perubahan
            PREV_COMMIT=$(git rev-parse HEAD)

            # 2. pull commit/kode terbaru dari branch main
            git pull origin main

            # 3. Cek apakah file compose/env berubah. Jika YA, jalankan docker compose up -d
            if git diff --name-only $PREV_COMMIT HEAD | grep -E '(docker-compose.prod.yml|\.env)'; then
              echo "Konfigurasi Docker/.env berubah. Reloading containers..."
              docker compose -f docker-compose.prod.yml up -d --wait
            fi

            # 4. Menginstal ulang dependency vendor jika ada perubahan composer.json
            docker compose -f docker-compose.prod.yml exec --user 1000:1000 app composer install --optimize-autoloader --no-dev

            # 5. Mengesekusi migrasi database otomatis
            docker compose -f docker-compose.prod.yml exec --user 1000:1000 app php artisan migrate --force

            # 6. Refresh & Optimize konfigurasi Laravel
            docker compose -f docker-compose.prod.yml exec --user 1000:1000 app php artisan optimize

# Zero-Downtime Deployment (Poin Utama): Untuk push harian yang hanya mengubah kode PHP/Laravel, Docker tidak akan restart. Aplikasi tetap menyala 100% tanpa ada downtime 50 detik.

# Otomatis & Efisien: Jika kamu mengubah file docker-compose.prod.yml atau .env, skrip git diff akan mendeteksinya secara otomatis dan baru menjalankan docker-compose.prod.yml up -d --wait

# Parameter --wait: Menjamin Docker menunggu status healthcheck MySQL & App healthy sebelum melangkah ke perintah Composer/Artisan berikutnya. Ini mencegah error connection refused.
